---
title: "Data manipulation with data.table"
comment: "*faster data wrangling with data.table!*"
output:
  html_document: 
    toc: yes
    toc_float: yes
    toc_depth: 6
    number_sections: yes
    code_folding: show
    theme: yeti
    df_print: paged

always_allow_html: true
---

```{r , include=FALSE}
library(tidyverse)
library(skimr)
# chunk options ----
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      tidy = FALSE,
                      fig.path = "img/")
# base options ----
base::options(
  tibble.print_max = 25,
  tibble.width = 78,
  scipen = 100000000,
  max.print = 999999
)
```

# Objectives

This document compares some data wrangling techniques between [`dplyr`](https://dplyr.tidyverse.org/index.html), [`tidyr`](https://tidyr.tidyverse.org/index.html), and [`data.table`](https://github.com/Rdatatable/data.table). 

## Load packages

These are all part of the `tidyverse`, so we install and load this meta-package below. We also install the `data.table` package.

```{r packages}
# install.packages(c("tidyverse", "data.table"))
library(tidyverse)
library(data.table)
```

https://github.com/Rdatatable/data.table

https://stackoverflow.com/questions/34598139/left-join-using-data-table


