---
title: "Lessons and Exercises"
---

```{r setup, include = FALSE, warning = FALSE}
library(tidyverse)
library(stringr)
library(htmltools)
tagList(rmarkdown::html_dependency_font_awesome())
```

```{r file-list, include = FALSE, warning = FALSE}
# first this defines three functions (has_all_things, parse_yaml, ext_file,  
# and cat_bullet)
has_all_things <- function(y, things) {
  all(match(tolower(things), tolower(y), nomatch = 0) > 0)
}

parse_yaml <- function(file, n = 30) {
  rmarkdown:::parse_yaml_front_matter(read_lines(file, n_max = n))
}

ext_file <- function(file, ext) {
  paste(file, ext, sep = ".")
}
```

```{r create-basenames_extensions, warning=FALSE, include=FALSE}
basenames_extensions <- tibble(fls = list.files("lessons-exercises")) %>%
  mutate(basename = tools::file_path_sans_ext(fls),
         basename = paste0("lessons-exercises/", basename),
         ext = tools::file_ext(fls)) %>% 
  group_by(basename) %>% 
  summarize_all(list) %>% 
  filter(map_lgl(ext, has_all_things, things = c("Rmd", "html")))

hrefs_bullets <- basenames_extensions %>% 
  mutate(
    yaml = basename %>% ext_file("Rmd") %>% map(parse_yaml),
    title = yaml %>% map_chr("title"),
    comment = yaml %>% map_chr("comment", .null = ""),
    comment = str_remove_all(string = comment, pattern = "Journalism 303: "),
    # comment = paste0("_*", comment, "*_"),
    comment = tolower(comment),
    href = map2(ext_file(basename, "html"), title, ~ a(href = .x, .y)) %>%
      map_chr(as.character),
    bullet = map2_chr(href, comment, ~ paste("*", .x, .y, "\n")))
# hrefs_bullets
```

```{r cat_bullet, warning=FALSE, include=FALSE}
cat_bullet <- function(x, pattern) {
  x <- hrefs_bullets %>% 
    filter(str_detect(basename, pattern = pattern)) %>%
  unnest(ext) %>%
    filter(ext == "html")
  cat(x$bullet)
}
```


### Week 1 (2021-08-23)

```{r wk1-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk1-")
```


### Week 2 (2021-08-30)

```{r wk2-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk2-")
```

### Week 3 (2021-09-06)

***Labor day, Campus closed***

### Week 3 (2021-09-13)

```{r wk3-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk3-")
```

### Week 4 (2021-09-20)

```{r wk4-files, results = 'asis', echo = FALSE}
cat_bullet(x, "^lessons-exercises/wk4-")
```

### Week 5 (2021-09-27)

```{r wk5-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk5-")
```

### Week 6 (2021-10-04)

```{r wk6-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk6-")
```

### Week 7 (2021-10-11)

*(under construction)*

```{r wk7-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk7-")
```

### Week 8 (2021-10-18)

*(under construction)*

```{r wk8-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk8-")
```

### Week 9 (2021-10-25)

```{r wk9-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk9-")
```

### Week 10 (2021-11-01)

```{r wk10-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk10-")
```

### Week 11 (2021-11-08)

```{r wk11-files, results = 'asis', echo = FALSE, eval=TRUE}
# and the `pr` for programming
cat_bullet(x, "^lessons-exercises/wk11-")
```

### Week 12 (2021-11-15)

```{r wk12-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk12-")
```

### Week 13 (2021-11-22)

```{r wk13-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk13-")
```

### Week 14 (2021-11-29)

```{r wk14-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk14-")
```

### Week 15 (2021-12-06)

```{r wk15-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk15-")
```

### Week 16 (2021-12-13)

```{r wk16-files, results = 'asis', echo = FALSE, eval=TRUE}
cat_bullet(x, "^lessons-exercises/wk16-")
```



This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).

