---
title: "Slides"
---

```{r setup, include = FALSE, warning = FALSE}
library(tidyverse)
library(stringr)
library(htmltools)
tagList(rmarkdown::html_dependency_font_awesome())
```

```{r file-list, include = FALSE, warning = FALSE}
# first this defines three functions (has_all_things, parse_yaml, ext_file,  
# and cat_bullet)
has_all_things <- function(y, things) {
  all(match(tolower(things), tolower(y), nomatch = 0) > 0)
}

parse_yaml <- function(file, n = 30) {
  rmarkdown:::parse_yaml_front_matter(read_lines(file, n_max = n))
}

ext_file <- function(file, ext) {
  paste(file, ext, sep = ".")
}
```

```{r create-basenames_extensions, warning=FALSE, include=FALSE}
basenames_extensions <- tibble(fls = list.files("slides")) %>%
  mutate(basename = tools::file_path_sans_ext(fls),
         basename = paste0("slides/", basename),
         ext = tools::file_ext(fls)) %>% 
  group_by(basename) %>% 
  summarize_all(list) %>% 
  filter(map_lgl(ext, has_all_things, things = c("Rmd", "html")))
# basenames_extensions
```

```{r create-hrefs_bullets, warning=FALSE, include=FALSE}
hrefs_bullets <- basenames_extensions %>% 
  mutate(
    yaml = basename %>% ext_file("Rmd") %>% map(parse_yaml),
    title = yaml %>% map_chr("title"),
    comment = yaml %>% map_chr("subtitle", .null = ""),
    comment = str_remove_all(string = comment, pattern = "Journalism 303: "),
    comment = paste0("*", comment, "*"),
    comment = tolower(comment),
    href = map2(ext_file(basename, "html"), title, ~ a(href = .x, .y)) %>%
      map_chr(as.character),
    bullet = map2_chr(href, comment, ~ paste("*", .x, .y, "\n")),
    href_pdf = map2(ext_file(basename, "pdf"), title, ~ a(href_pdf = .x, .y)) %>%
      map_chr(as.character),
    href_pdf = str_replace_all(string = href_pdf, "href_pdf", "href"),
    href_pdf = str_replace_all(string = href_pdf, "slides/", "slides/pdfs/"),
    bullet_pdf = map2_chr(href_pdf, comment, ~ paste("*", .x, .y, "\n")),
    bullet_pdf = str_replace_all(string = bullet_pdf, "href_pdf", "href"),
    bullet_pdf = str_remove_all(string = bullet_pdf, pattern = "_pdf")
    )
# hrefs_bullets
```

```{r cat_bullets, warning=FALSE, include=FALSE}
cat_bullet <- function(x, pattern) {
  x <- x %>% 
    filter(str_detect(basename, pattern = pattern)) %>%
  unnest(ext) %>%
    filter(ext == "html")
  cat(x$bullet)
}

cat_bullet_pdf <- function(x, pattern) {
  x <- x %>% 
    filter(str_detect(basename, pattern = pattern)) %>%
  unnest(ext) %>%
    filter(ext == "html")
  cat(x$bullet_pdf)
}
```

## Week 1 (2021-08-23)


```{r wk-01-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-01")
```

##### PDFS

```{r cat_bullet_pdf-01, results='asis', echo=FALSE, eval=TRUE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-01")
```


## Week 2 (2021-08-30)


```{r wk-02-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-02")
```

##### PDFS

```{r cat_bullet_pdf-02, results='asis', echo=FALSE, eval=TRUE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-02")
```

## Week 3 (2021-09-06)

***Labor day, Campus closed***

## Week 3 (2021-09-13)


```{r wk-03-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-03")
```

##### PDFS

```{r cat_bullet_pdf-03, results='asis', echo=FALSE, eval=TRUE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-03")
```

## Week 4 (2021-09-20)

```{r wk-04-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-04")
```

##### PDFS

```{r cat_bullet_pdf-04, results='asis', echo=FALSE, eval=TRUE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-04")
```

## Week 5 (2021-09-27)

```{r wk-05-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-05")
```

##### PDFS

```{r cat_bullet_pdf-05, results='asis', echo=FALSE, eval=TRUE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-05")
```

## Week 6 (2021-10-04)

```{r wk-06-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-06")
```

##### PDFS

```{r cat_bullet_pdf-06, results='asis', echo=FALSE, eval=TRUE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-06")
```

## Week 7 (2021-10-11)

```{r wk-07-files, results='asis', echo=FALSE, eval=TRUE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-07")
```

##### PDFS

```{r cat_bullet_pdf-07, results='asis', echo=FALSE, eval=TRUE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-07")
```

## Week 8 (2021-10-18)

*(under construction)*

```{r wk-08-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-08")
```

##### PDFS

```{r cat_bullet_pdf-08, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-08")
```

## Week 9 (2021-10-25)

*(under construction)*

```{r wk-09-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-09")
```

##### PDFS

```{r cat_bullet_pdf-09, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-09")
```

## Week 10 (2021-11-01)

```{r wk-10-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-10")
```

##### PDFS

```{r cat_bullet_pdf-10, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-10")
```


## Week 11 (2021-11-08)

```{r wk-11-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-11")
```

##### PDFS

```{r cat_bullet_pdf-11, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-11")
```

## Week 12 (2021-11-15)

```{r wk-12-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-12")
```

##### PDFS

```{r cat_bullet_pdf-12, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-12")
```

## Week 13 (2021-11-22)

```{r wk-13-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-13")
```

##### PDFS

```{r cat_bullet_pdf-13, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-13")
```

## Week 14 (2021-11-29)

```{r wk-14-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-14")
```

##### PDFS

```{r cat_bullet_pdf-14, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-14")
```

## Week 15 (2021-12-06)

```{r wk-15-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-15")
```

##### PDFS

```{r cat_bullet_pdf-15, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-15")
```

## Week 16 (2021-12-13)

```{r wk-16-files, results='asis', echo=FALSE, eval=FALSE}
cat_bullet(x = hrefs_bullets, pattern = "^slides/wk-16")
```

##### PDFS

```{r cat_bullet_pdf-16, results='asis', echo=FALSE, eval=FALSE}
cat_bullet_pdf(x = hrefs_bullets, pattern = "^slides/wk-16")
```
