---
title: "My Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(inspectdf)
library(reactable)
library(janitor)
```

Inputs {.sidebar data-width=200}
=====================================

Data input.

```{r AppleMobRaw, message=FALSE, warning=FALSE}
AppleMobRaw <- readr::read_csv("https://bit.ly/36tTVpe")
AppleMobRaw %>% 
  # transpose data 
  tidyr::pivot_longer(cols = -c(geo_type:country), 
    names_to = "date", values_to = "dir_request") %>% 
    # remove missing country data
  dplyr::filter(!is.na(country) & !is.na(`sub-region`)) %>% 
  # clean names
  janitor::clean_names() %>%
  # date
  mutate(date = lubridate::ymd(date)) %>% 
  # create trans_type
  rename(trans_type = transportation_type) -> TidyApple
```


Page 1 {data-orientation=columns}
=======================================================================


Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Memory Size

```{r inspect_mem}
TidyApple %>%  
  inspectdf::inspect_mem() %>%  
  inspectdf::show_plot(text_labels = TRUE)
```

### Missing Data

```{r inspect_na}
TidyApple %>%
  inspectdf::inspect_na() %>% 
  inspectdf::show_plot(text_labels = TRUE)
```


Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Categorical Data

```{r inspect_cat}
TidyApple %>% 
  select_if(is.character) %>% 
  inspectdf::inspect_cat() %>% 
  inspectdf::show_plot(text_labels = TRUE)
```

### Data Imbalances

```{r inspect_imb}
TidyApple %>% 
  inspectdf::inspect_imb() %>% 
  inspectdf::show_plot(text_labels = TRUE)
```


Page 2 {data-orientation=rows}
=======================================================================

Row {.tabset .tabset-fade data-height=600}
-----------------------------------------------------------------------

### Numeric Data

```{r}
TidyApple %>% 
  select_if(is.numeric) %>% 
  inspectdf::inspect_num() %>% 
  inspectdf::show_plot(text_labels = TRUE)
```

### Distributions `ggridges`

```{r ggridges, message=FALSE, warning=FALSE}
library(ggridges) 
lab_ridges <- labs(x = "Apple directions requests",
                   y = "Transportation Types",
     title = "Direction Requests by Transportation Type",
     subtitle = "source: https://covid19.apple.com/mobility")


TidyApple %>%
  ggplot() +
  geom_density_ridges(aes(x = dir_request, 
                          y = trans_type,
    fill = trans_type), 
    alpha = 1/5) +
  lab_ridges
```

Row {.tabset .tabset-fade data-height=400}
-----------------------------------------------------------------------

### `TopUSCities` as `paged_table`

```{r TopUSCities}
TopUSCities <- TidyApple %>% 
  filter(country == "United States" & 
           region %in% c("New York City","Los Angeles", 
                         "Chicago", "Houston", "Phoenix"))
rmarkdown::paged_table(TopUSCities)
```


### `MaxUSCitiesDriving` as `reactable`

```{r MaxUSCitiesDriving}
TopUSCities %>% 
  filter(trans_type == "driving") %>% 
  group_by(region) %>% 
  slice_max(dir_request) %>% 
  ungroup() -> MaxUSCitiesDriving
reactable(MaxUSCitiesDriving, 
              resizable = TRUE, showPageSizeOptions = TRUE, 
              selection = "multiple", onClick = "select")
```

Page 3 {data-navmenu='More'}
=======================================================================


Column
-----------------------------------------------------------------------

### Chart E

```{r TopUSCities-facet, fig.width=10, fig.height=7}
lab_top_cities <- labs(x = "Date", y  = "Direction Requests", 
     title = "Trends of Relative Activity in Selected US Cities",
     subtitle = "NY, LA, CH, HOU, PHA, PHL, SATX, SD", 
     color = "Type")

TopUSCities %>% 
  ggplot(aes(x = date, y = dir_request, 
             group = region, 
             color = trans_type)) + 
  geom_line(size = 0.1) + 
  geom_hline(yintercept = 100, size = 0.2, color = "gray20") +
  facet_wrap(region ~ trans_type, ncol = 6) + 
  theme_minimal() + 
  theme(legend.position = "top") +
  lab_top_cities 
```

Page 4 {data-navmenu='More'}
=======================================================================

Column
-----------------------------------------------------------------------

### Chart F

```{r hrbrthemes, fig.width=10, fig.height=7}
library(hrbrthemes)
TopUSCities %>% 
  ggplot(aes(x = date, y = dir_request, 
             group = region, 
             color = trans_type)) + 
  geom_line(size = 0.1) + 
  geom_hline(yintercept = 100, size = 0.2, color = "gray20") +
  facet_wrap(region ~ trans_type, ncol = 6) + 
  hrbrthemes::theme_ipsum(
    base_size = 8, 
    plot_title_size = 12, 
    strip_text_size = 9, 
    subtitle_size = 10) + 
  theme(legend.position = "top") +
  lab_top_cities 
```


